todolist/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("unidad_medida/", views.unidad_medida_view, name="unidad_medida"),
    path("insert/", views.insert, name="insert"),
    path("update", views.update, name="update"),
    path("update/<int:task_id>", views.update_form, name="update_form"),
    path("delete/<int:task_id>", views.delete, name="delete"),
    
    path("centrodecostos/", views.centrodecostos_view, name='centrodecostos_view'),
    path("centrodecostos_insert/", views.centrodecostos_insert, name="centrodecostos_insert"),
    path("centrodecostos_update", views.centrodecostos_update, name="centrodecostos_update"),
    path("centrodecostos_update_form/<int:centro_costos_id>", views.centrodecostos_update_form, name="centrodecostos_update_form"),
    path("centrodecostos_delete/<int:centro_costos_id>", views.centrodecostos_delete, name="centrodecostos_delete"),
   
    #path("conceptos/", views.conceptos_view, name='conceptos_view'),

    #path("conceptos_insert/", views.conceptos_insert, name="conceptos_insert"),
    path("concepto/", views.conceptos_view, name='conceptos_view'),
    path("conceptos_delete/<int:conceptosForm_id>", views.conceptos_delete, name="conceptos_delete"),
    path("conceptos_edit/<int:conceptosForm_id>", views.conceptos_edit, name="conceptos_edit"),




    
    path('eliminar_registro/<int:pk>/', views.eliminar_registro, name='eliminar_registro'),
    path('grupos_centros/', views.agregar_registro, name='grupos_centros'),
    path('grupos_edit/<int:pk>/', views.grupos_edit, name='grupos_edit'),
    path('grupos_delete/<int:gruposForm_id>', views.grupos_delete, name='grupos_delete'),



]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("app.urls")),
    path('admin/', admin.site.urls),
]

todolist/app/models.py
from django.db import models

from django.db import models

class Task(models.Model):
    subject = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.subject

class Centro_costos(models.Model):
    unidad = models.CharField(max_length=100)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='centro_costos')

    def __str__(self):
        return self.unidad

class Grupos_detalle(models.Model):
    nombre = models.CharField(max_length=255)
    porcentaje_acumulado = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return self.nombre

class Grupos_registro(models.Model):
    detalle = models.ForeignKey(Grupos_detalle, on_delete=models.CASCADE)
    centro_costos = models.ForeignKey(Centro_costos, on_delete=models.SET_NULL, null=True, blank=True)
    porcentaje = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return str(self.detalle)

class Concepto(models.Model):
    codigo_ex = models.CharField(max_length=100)

    centro_costos = models.ForeignKey(Centro_costos, on_delete=models.CASCADE, related_name='conceptos', null=True, blank=True)
    grupos_detalle = models.ForeignKey(Grupos_detalle, on_delete=models.CASCADE, related_name='grupos_detalle', null=True, blank=True)

    def __str__(self):
        return self.codigo_ex
    

todolist/app/forms.py
from django import forms
from .models import Concepto,Grupos_registro,Grupos_detalle
from django.core.exceptions import ValidationError
from django.db.models import Sum
from django.contrib import messages
class DetalleForm(forms.Form):
    nombre = forms.CharField(
        max_length=255,
        required=True,
        label='<b>Descripcion grupo</b>',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
 

class RegistroForm(forms.ModelForm):
    # ... Resto del código del formulario ...

    class Meta:
        model = Grupos_registro
        fields = ['detalle', 'centro_costos', 'porcentaje']
        
        widgets = {
            'detalle': forms.Select(attrs={'class': 'form-control'}),
            'porcentaje': forms.NumberInput(attrs={'step': 1 ,'class': 'form-control'}),
            'centro_costos': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['centro_costos'].label_from_instance = lambda obj: f"{obj.unidad}"

    def as_custom_p(self):
        # Selecciona los campos que deseas incluir en el formato personalizado
        fields = ['detalle', 'centro_costos', 'porcentaje']
        return self._html_output(
            normal_row=self._html_output(fields, 'form-row', 'form-row', 'form-group'),
            error_row='%s',
            row_ender='</div>',
            help_text_html=' %s',
            errors_on_separate_row=True,
        )

  
    
       


    ''' def clean_porcentaje(self):
        porcentaje = self.cleaned_data['porcentaje']
        detalle = self.cleaned_data['detalle']
        centro_costos = self.cleaned_data.get('centro_costos')
        porcentaje_acumulado = detalle.porcentaje_acumulado + porcentaje
        if  centro_costos is None:
            raise forms.ValidationError("Por favor, selecciona un centro de costos.")
        if porcentaje_acumulado > 100:
            raise forms.ValidationError("El porcentaje total excede el 100%.")
        
        return porcentaje
       '''

#--------------------------------------------------
from django import forms

class ConceptoForm(forms.ModelForm):
    class Meta:
        model = Concepto
        fields = ['codigo_ex', 'centro_costos', 'grupos_detalle']
        labels = {
            'codigo_ex': 'CodigoExterno:',
            'centro_costos': 'Centro de costos :',
            'grupos_detalle': 'Grupo :',
        }

        widgets = {
            'codigo_ex': forms.TextInput(attrs={'class': 'form-control'}),
            'centro_costos': forms.Select(attrs={'class': 'form-control'}),
            'grupos_detalle': forms.Select(attrs={'class': 'form-control'}),
        }
    
   
#--------------------------

todolist/app/templates/app/agregar_grupo.html
<form method="post" action="{% url 'agregar_grupo' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>

todolist/app/templates/app/agregar_registro copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>TAO</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <!-- DataTable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,500;1,400;1,500&display=swap" rel="stylesheet">
    <!-- Custom CSS 
    <link rel="stylesheet" href="{%static 'css/estilos.css'%}">-->
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"> 
    
</head>

<body>
    {% include 'app/navchar.html' %}
    <!-- Formulario de Registro -->
    <form method="post" action="{% url 'agregar_registro' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Registro</button>
    </form>

    <!-- Tabla de Registros -->
    <h3>Registros existentes:</h3>
    <table id="filterTable">
        <thead>
            <tr>
                <th>Detalle</th>
                <th>Grupos Nombre</th>
                <th>Centro Costos</th>
                <th>Porcentaje</th>
            </tr>
        </thead>
        <tbody>
            {% for detalle in grupos_detalles %}
                <tr>
                    <td>{{ detalle.nombre }}</td>
                    <td>
                        {% for registro in detalle.grupos_registro_set.all %}
                            {{ registro.grupos_nombre }}
                            <!-- Puedes agregar más detalles aquí si es necesario -->
                        {% endfor %}
                    </td>
                    <td>{% if detalle.grupos_registro_set.all.0.centro_costos %}{{ detalle.grupos_registro_set.all.0.centro_costos.nombre }}{% endif %}</td>
                    <td>{{ detalle.porcentaje_acumulado }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Mostrar Totales -->
    <p>Total Porcentaje: {{ total_porcentaje }}%</p>
    <p>Falta Porcentaje: {{ falta_porcentaje }}%</p>

    <!-- jQuery y DataTables JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>

    <!-- Configuración de DataTables -->
    <script>
       $(document).ready(function() {
    var table = $('#filterTable').DataTable({
        ordering: false
    });

    // Oculta las columnas de hijas al inicio
    $('#filterTable thead th:not(:first-child)').hide();
    $('#filterTable tbody tr.parent td:not(:first-child)').hide();

    // Agrega el evento de clic para abrir y cerrar detalles
    $('#filterTable tbody').on('click', 'tr.parent', function() {
        var tr = $(this);
        var row = table.row(tr);

        if (row.child.isShown()) {
            // Esta fila ya está abierta, ciérrala
            row.child.hide();
            tr.removeClass('shown');
        } else {
            // Abre esta fila
            row.child(format(row.data())).show();
            tr.addClass('shown');
        }
    });

    // Función para formatear los detalles
    function format(data) {
        return (
            '<dl>' +
            '<dt>Nombre:</dt>' +
            '<dd>' + data[1] + '</dd>' +  // Ajusta el índice según tus datos
            '<dt>Centro Costos:</dt>' +
            '<dd>' + data[2] + '</dd>' +  // Ajusta el índice según tus datos
            '<dt>Porcentaje:</dt>' +
            '<dd>' + data[3] + '</dd>' +  // Ajusta el índice según tus datos
            '</dl>'
        );
    }
});
    </script>

    <script src="{% static 'js/config.js' %}"></script>
    {% include 'app/footer.html' %}
</body>

</html>


































<!DOCTYPE html>
<html lang="en">
<head>
    <title>DataTables Ejemplo</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
</head>
<body>

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Nombre</th>
            <th style="display:none;">Posición</th>
            <th style="display:none;">Oficina</th>
            <th >Porcentaje</th>
        
        </tr>
    </thead>
    <tbody>
        {% for detalle in grupos_detalles %}
        <tr>
            <td>{{ detalle.nombre }}</td>
            <td style="display:none;">{% for registro in detalle.grupos_registro_set.all %}{{ registro.grupos_nombre }}<!-- Puedes agregar más detalles aquí si es necesario -->{% endfor %}</td>
            <td style="display:none;">{% if detalle.grupos_registro_set.all.0.centro_costos %}{{ detalle.grupos_registro_set.all.0.centro_costos.nombre }}{% endif %}</td>
            <td >{{ detalle.porcentaje_acumulado }}</td>
            
        </tr>
    {% endfor %}
      
        <!-- Otras filas... -->
    </tbody>
</table>

<script>
    $(document).ready(function() {
        var table = $('#example').DataTable({
            ordering: false
        });

        // Agrega el evento de clic para abrir y cerrar detalles
        $('#example tbody').on('click', 'td', function() {
            var tr = $(this).closest('tr');
            var row = table.row(tr);

            if (row.child.isShown()) {
                // Esta fila ya está abierta, ciérrala
                row.child.hide();
                tr.removeClass('shown');
            } else {
                // Abre esta fila
                row.child(format(row.data())).show();
                tr.addClass('shown');
            }
        });

        // Función para formatear los detalles
        function format(d) {
            return (
                '<dl>' +
                '<dt>Nombre completo:</dt>' +
                '<dd>' + d[0] + '</dd>' +
                '<dt>Posición:</dt>' +
                '<dd>' + d[1] + '</dd>' +
                '<dt>Oficina:</dt>' +
                '<dd>' + d[2] + '</dd>' +
                '<dt>Edad:</dt>' +
                '<dd>' + d[3] + '</dd>' +
                
                '</dl>'
            );
        }
    });
</script>

</body>
</html>





























<!DOCTYPE html>
<html lang="en">
<head>
    <title>DataTables Ejemplo</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
</head>
<body>

    <form method="post" action="{% url 'agregar_registro' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Registro</button>
    </form>

    <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Porcentaje</th>
                <th style="display:none;">Centro Costos</th>
            </tr>
        </thead>
        <tbody>
            {% for detalle in grupos_detalles %}
            <tr>
                <td>{{ detalle.nombre }}</td>
                <td>{{ detalle.porcentaje_acumulado }}</td>
                <td style="display:none;">
                    {% for registro in detalle.grupos_registro_set.all %}
                        {{ registro.centro_costos }} : {{ registro.porcentaje }}%
                        {% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        $(document).ready(function() {
            var table = $('#example').DataTable({
                ordering: false
            });
    
            // Agrega el evento de clic para abrir y cerrar detalles
            $('#example tbody').on('click', 'td', function() {
                var tr = $(this).closest('tr');
                var row = table.row(tr);
    
                if (row.child.isShown()) {
                    // Esta fila ya está abierta, ciérrala
                    row.child.hide();
                    tr.removeClass('shown');
                } else {
                    // Abre esta fila
                    row.child(format(row.data())).show();
                    tr.addClass('shown');
                }
            });
    
            // Función para formatear los detalles
            function format(d) {
                if (d[2]) {
                    return (
                        '<dl>' +
                        '<dt>Centro de Costos:</dt>' +
                        '<dd>' + d[2] + '</dd>' +
                        
                        '</dl>'
                    );
                } else {
                    return '<p>No hay detalles disponibles</p>';
                }
            }
        });
    </script>
    

</body>
</html>

todolist/app/templates/app/footer.html
<footer class="dark-background text-dark py-3 custom-footer mt-1">
    <div class="container">
        <p >&copy; 2024 Tao Software</p>
    </div>
</footer>

todolist/app/templates/app/grupos_centros.html
{% extends 'app/home.html' %} <!--Trae el template-->
{% block cuadro_style_custom %} <!--CSS Custom para este html-->

  
    


<style>
 /* Estilos personalizados para ajustar la altura del cuadro de texto */
 #id_detalle,
#id_nombre,
#id_porcentaje,
#id_centro_costos {
    height: 30px;
    margin: 0;
    padding: 2px 12px; /* Ajusta según sea necesario */
    vertical-align: middle;
    }

</style>      
{% endblock cuadro_style_custom %}
{% block titulo %}
    Grupos de centros de costos
{% endblock titulo %}

{% block cuadro_contenido %}
<div class="col-md-12">
    <div class="container my-4">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <!-- Formulario para agregar un nuevo grupo -->
                    <div class="row">
                        <div class="col-md-4">
                            <form method="post" action="{% url 'grupos_centros' %}">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <label for="{{ detalle_form.nombre.id_for_label }}" class="form-label"><b>Descripcion grupo</b></label>
                                    {{ detalle_form.nombre }}
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-secondary" type="submit"><i class="fas fa-plus"></i> Agregar Grupo</button>
                                </div>
                            </form>
                        </div>
                    
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-4">
                            <!-- Contenido del primer cuadro (formulario) -->
                            <form method="post" action="{% url 'grupos_centros' %}">
                                {% csrf_token %}
                                <!-------------------------------->
                                    <div class="row " >
                                        <label for="subject" class="form-label"><b>Seleccionar grupo</b></label>
                                        <div class="form-group col-md-12">
                                            {{ form.detalle }}
                                        </div>
                                    </div>
                                <!-------------------------------->
                                
                                    <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group mb-3">
                                            <label for="subject" class="form-label"><b>Centro de costos</b></label>
                                            {{ form.centro_costos }}
                                        </div>
                                    </div>
                                <!-------------------------------->
                                    <div class="col-md-4">
                                        <div class="form-group mb-3">
                                            <label for="subject" class="form-label"><b>Porcentaje</b></label>
                                            {{ form.porcentaje }}
                                        </div>
                                    </div>
                                </div>
                                {% if messages %}
                                    <div class="messages">
                                        {% for message in messages %}
                                            {% if 'custom-success' in message.tags %}
                                                <div class="alert alert-success">
                                                    <i class="fas fa-check-circle fa-lg"></i> {{ message }}
                                                </div>
                                            {% elif 'custom-error' in message.tags %}
                                                <div class="alert alert-danger">
                                                    <i class="fas fa-times-circle fa-lg"></i> {{ message }}
                                                </div>
                                            {% else %}
                                                <!---<div class="alert">{{ message }}</div>-->
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                
                                <button class="btn btn-secondary" type="submit"><i class="fas fa-save fa-lg"></i> Agregar centro a grupo</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container my-4">
    <div class="row">
        <div class="card">
            <div class="card-body">
                        
                <!----------------------------------------------------------------->
                    <table id="example" class="display" style="width:100%">
                        <thead>
                            <tr>
                                <th class="centered bg-secondary white-text">&nbsp; Nombre</th>
                                <th class="centered bg-secondary white-text ">Porcentaje</th>
                                <th style="display:none;"class="centered bg-secondary white-text" ></th>
                                <th class="centered bg-secondary white-text rounded-top-right" ></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for detalle in grupos_detalles %}
                               
                                    <tr class="fila-madre">
                                        <td>{{ detalle.nombre }}</td>
                                        <td>
                                            {{ detalle.porcentaje_acumulado|floatformat }}%
                                            {% if detalle.porcentaje_acumulado == 100 %}
                                                <i class="fas fa-check text-secondary"></i>
                                            {% endif %}
                                        </td>
                                        <td style="display:none;">
                                            {% for registro in detalle.grupos_registro_set.all %}
                                                {{ registro.centro_costos }} : ({{ registro.porcentaje|floatformat }}%)
                                                {% if not forloop.last %}<br>{% endif %}
                                            {% endfor %}
                                        </td>
                                        <td class="text-right text-sm">                                        
                                          <!--  <a href="{% if detalle.id %}{% url 'grupos_edit' detalle.id %}{% endif %}" class="btn btn-sm btn-secondary"><i class="fas fa-pen"></i></a> -->
                                            <a href="{% if detalle.id %}{% url 'grupos_delete' detalle.id %}{% endif %}" class="btn btn-sm btn-danger eliminarConfirmacion"> <i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                
                            {% endfor %}
                        </tbody>   
                        <caption>DataTable TAO</caption>                            
                    </table>
                    
                    <!----------------------------------------------------------------->
                        </div>
                    
                </div>
            </div>
        </div>
<script>
    $(document).ready(function() {
        $.extend(true, $.fn.dataTable.defaults, {
            language: {
                zeroRecords: "Ningún registro encontrado",
                
                infoEmpty: "Ningún registro encontrado",
                infoFiltered: "(filtrados desde _MAX_ registros totales)",
                loadingRecords: "Cargando...",
                
            },
            lengthChange: false,  // Oculta "Show entries"
            searching: false,     // Oculta "Search"
            paging: false ,         // Oculta los controles de paginación
            info: false
        });

        // Resto de tu código DataTables...
    });
               // Función para formatear los detalles
               $(document).ready(function() {
       var table = $('#example').DataTable({
           ordering: false
       });
   
       // Agrega el evento de clic para abrir y cerrar detalles
       $('#example tbody').on('click', 'td.details-control', function() {
           var tr = $(this).closest('tr');
           var row = table.row(tr);
   
           // Cambia el icono a "+" o "-" según el estado de la fila
           var iconElement = tr.find('.icon-toggle');
           iconElement.toggleClass('fa-plus-circle fa-minus-circle');
   
           if (row.child.isShown()) {
               // Esta fila ya está abierta, ciérrala
               row.child.hide();
               tr.removeClass('shown');
           } else {
               // Abre esta fila
               row.child(format(row.data())).show();
               tr.addClass('shown');
           }
       });
   
       // Función para formatear los detalles
       function format(d) {
           if (d[2]) {
               return (
                   '<dl>' +
                   '<dt>Centro de Costos:</dt>' +
                   '<dd>' + d[2] + '</dd>' +
                   '</dl>'
               );
           } else {
               return '<p>No hay detalles disponibles</p>';
           }
       }
   
       // Agrega un botón de expansión en la primera celda de cada fila
       $('#example tbody tr').each(function() {
           var firstCell = $(this).find('td:first-child');
           firstCell.addClass('details-control');
           firstCell.html('<i class="fas fa-plus-circle fa-lg icon-toggle text-secondary"></i> ' + firstCell.html());
       });
   
       // Agrega el evento de clic para abrir y cerrar detalles cuando se hace clic en el icono
       $('#example tbody').on('click', 'td.details-control .icon-toggle', function(e) {
           e.stopPropagation(); // Evita que el clic se propague a la fila completa
           $(this).closest('td.details-control').trigger('click');
       });
   });
   
</script>

{% endblock cuadro_contenido %}




VALIDACIONES  PARA NO PERDER
{% for detalle in grupos_detalles %}
{% if detalle.grupos_registro_set.all|length > 0 or detalle.porcentaje_acumulado > 0 %}
    <tr class="fila-madre">
        <td>{{ detalle.nombre }}</td>
        <td>
            {{ detalle.porcentaje_acumulado|floatformat }}%
            {% if detalle.porcentaje_acumulado == 100 %}
                <i class="fas fa-check text-secondary"></i>
            {% endif %}
        </td>
        <td style="display:none;">
            {% for registro in detalle.grupos_registro_set.all %}
                {{ registro.centro_costos }} : ({{ registro.porcentaje|floatformat }}%)
                {% if not forloop.last %}<br>{% endif %}
            {% endfor %}
        </td>
        <td class="text-right text-sm">                                        
          <!--  <a href="{% if detalle.id %}{% url 'grupos_edit' detalle.id %}{% endif %}" class="btn btn-sm btn-secondary"><i class="fas fa-pen"></i></a> -->
            <a href="{% if detalle.id %}{% url 'grupos_delete' detalle.id %}{% endif %}" class="btn btn-sm btn-secondary eliminarConfirmacion"> <i class="fas fa-trash"> Borrar</i></a>
        </td>
    </tr>
{% endif %}
{% endfor %}

todolist/app/templates/app/index.html
{% extends 'app/home.html' %}

{% block titulo %}

{% endblock titulo %}

{% block cuadro_contenido %} 
<div class="container main-content outer-container">
    <!-- Contenedor principal con barra de navegación y contenido adicional (tarjeta) -->
    <div class="row">
        
        <div class="col-md-12">
            <div class="container my-4">
                <div class="row align-items-center text-center">
                    <div class="card-body" style="position: relative; display: flex; flex-direction: column-reverse; align-items: center;">
                        <div style="text-align: center;">
                            <h5 style="position: absolute; bottom: 0; right: 0; margin-top: 230 20px 20px 0;">
                                <b>“Todo lo que puedas medir, puedes mejorarlo.”       
                            </h5>
                            <h5 style="position: absolute; bottom: 6; right: 0; margin: -230 20px 20px 0;">
                               <b> 
                                    Peter Drucker</b>
                            </h5>
                            <h5 style="margin-top: -260px; margin-bottom: -20px;">
                                <b>En TAO software estamos convencidos que poder identificar y comprender los costos indirectos de una empresa es fundamental para tomar decisiones y definir estrategias que impacten positivamente en su rentabilidad y competitividad.</b>
                            </h5>
                            
                        </div>
                        <img src="http://sistek.no-ip.org/leon.jpg" class="img-fluid" style="max-width: 50%; height: auto; opacity: 0.1; margin-top: -1cm;">
                    </div>
                    
                </div>                               
            </div>           
        </div>
    </div>
</div>
{% endblock cuadro_contenido %}

todolist/app/templates/app/upload_file.html
<!-- upload_file.html -->
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Cargar archivo</button>
</form>